# -*- coding: utf-8 -*-
"""Bolero.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jRwJLRskJfn_lgh6gzAQoMRwydYSqREu
"""

from fractions import Fraction

def bolero(gauge_s: int, gauge_r: int, armpit: int, bicep: int, length: int, arm_length: int, wrist: int, n_ease: int, fitted):
  armpit_sts = (armpit-n_ease)*gauge_s/10
  if fitted == False:
    row = (length/10)*gauge_r
    arm_row = (arm_length/10)*gauge_r
    double_sew_rows = (6/10)*gauge_r
    text = f"""Cast on {armpit_sts} sts.
    Knit in stockinette for {row} rows.
    Sew {arm_row} rows from both ends. The last {double_sew_rows} sts sew 2 bottom sts to 1 top sts."""
  if fitted == True:
    wrist_sts = (wrist*gauge_s)/10
    row = (length/10)*gauge_r
    dec = (armpit_sts - wrist_sts)/row
    print(dec)
    f = Fraction(dec).limit_denominator(10)
    print(f)
    arm_row = (arm_length/10)*gauge_r
    double_sew_rows = (6/10)*gauge_r
    text = f"""
    Cast on {armpit_sts} sts.
    Knit in stockinette for {row} rows.
    Decrease {f.numerator} sts every {f.denominator} row.
    Sew {arm_row} rows from both ends. The last {double_sew_rows} sts sew 2 bottom sts to 1 top sts.
    """

  print(text)

if __name__ == "__main__":
  #10cm gauge
  gauge_s = 10
  gauge_r = 10

  #bolero measurement in cm
  armpit = 39
  bicep = 33
  n_ease = 4
  length = 125
  arm_length = 39
  wrist = 14

  #modifications
  fitted = True

  bolero(gauge_s, gauge_r, armpit, bicep, length, arm_length, wrist, n_ease, fitted)

